/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gameoflife;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author victor
 */
public class Board extends javax.swing.JPanel {
    
    private ViewModelMatrix viewModelMatrix;

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        int numRows = ConfigData.getInstance().getNumRows();
        int numCols = ConfigData.getInstance().getNumCols();
        viewModelMatrix = new ViewModelMatrix(numRows, numCols);
    }
    

    @Override
    protected void paintComponent(Graphics g) {
        paintBackground(g);
    }
    
    private void paintBackground(Graphics g) {
        int width = getWidth();
        int height = getHeight();
        int numRows = ConfigData.getInstance().getNumRows();
        int numCols = ConfigData.getInstance().getNumCols();
        int squareWidth = width / numCols;
        int squareHeight = height / numRows;
        int realWidth = squareWidth * numCols;
        int realHeight = squareHeight * numRows;
        int leftMargin = (width - realWidth) / 2;
        int upperMargin = (height - realHeight) / 2;
        g.setColor(Color.WHITE);
        g.fillRect(leftMargin, upperMargin, realWidth, realHeight);
        
        // Paint grid
        g.setColor(Color.LIGHT_GRAY);
        for (int row = 0; row < numRows; row ++) {
            g.drawLine(leftMargin, upperMargin + row * squareHeight ,
                    realWidth + leftMargin,  upperMargin + row * squareHeight );
        }
        for (int col = 0; col < numCols; col ++) {
            g.drawLine(leftMargin + col * squareWidth, upperMargin, 
                    leftMargin + col * squareWidth, upperMargin + realHeight);
        }
        
        // Paint frame
        g.setColor(Color.BLACK);
        g.drawRect(leftMargin, upperMargin, realWidth, realHeight);
        
        System.out.println("width: " + width);
        System.out.println("Real width: " + realWidth);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
