package com.mycompany.gameoflife;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author victor
 */
public class Board extends javax.swing.JPanel {
    
    class Dimensions {
        int width = getWidth();
        int height = getHeight();
        int numRows = ConfigData.getInstance().getNumRows();
        int numCols = ConfigData.getInstance().getNumCols();
        int squareWidth = width / numCols;
        int squareHeight = height / numRows;
        int realWidth = squareWidth * numCols;
        int realHeight = squareHeight * numRows;
        int leftMargin = (width - realWidth) / 2;
        int upperMargin = (height - realHeight) / 2;
    }
    
    private ViewModelMatrix viewModelMatrix;

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        int numRows = ConfigData.getInstance().getNumRows();
        int numCols = ConfigData.getInstance().getNumCols();
        viewModelMatrix = new ViewModelMatrix(numRows, numCols);
        viewModelMatrix.fillRandom(0.25f);
    }
    

    @Override
    protected void paintComponent(Graphics g) {
        Dimensions dimensions = new Dimensions();
        paintBackground(g, dimensions);
        paintCells(g, dimensions);
    }
    
    private void paintCells(Graphics g, Dimensions d) {
        g.setColor(Color.BLACK);
        for (int row = 0; row < d.numRows; row++) {
            for (int col = 0; col < d.numCols; col++) {
                if (viewModelMatrix.isAlive(row, col)) {
                    g.fillRect(d.leftMargin + col * d.squareWidth, 
                            d.upperMargin + row * d.squareHeight,
                            d.squareWidth, d.squareHeight);
                }
            }
        }
    }
    
    private void paintBackground(Graphics g, Dimensions d) {
        
        g.setColor(Color.WHITE);
        g.fillRect(d.leftMargin, d.upperMargin, d.realWidth, d.realHeight);
        
        // Paint grid
        g.setColor(Color.LIGHT_GRAY);
        for (int row = 0; row < d.numRows; row ++) {
            g.drawLine(d.leftMargin, d.upperMargin + row * d.squareHeight ,
                    d.realWidth + d.leftMargin,  d.upperMargin + row * d.squareHeight );
        }
        for (int col = 0; col < d.numCols; col ++) {
            g.drawLine(d.leftMargin + col * d.squareWidth, d.upperMargin, 
                    d.leftMargin + col * d.squareWidth, d.upperMargin + d.realHeight);
        }
        
        // Paint frame
        g.setColor(Color.BLACK);
        g.drawRect(d.leftMargin, d.upperMargin, d.realWidth, d.realHeight);
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
